name: "on-pull-request"

on:
  pull_request:

jobs:
  fmt:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.24.2"

      - name: "Install golangci-lint"
        run: "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest"

      - name: "Run golangci-lint fmt"
        id: "fmt-diff"
        continue-on-error: true
        working-directory: "./backend"
        run: "golangci-lint fmt --diff ./..."

      - name: "Check if format failed"
        if: "steps.fmt-diff.outcome == 'failure'"
        run: |
          echo "golangci-lint fmt: ${{ steps.ut-result.outcome }}"
          exit 1

  lint:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.24.2"

      - name: "Check lint"
        uses: "golangci/golangci-lint-action@v7"
        with:
          working-directory: "./backend"
          version: "latest"
          skip-cache: true
          args: "--timeout 2m"

  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.24.2"

      - name: "Run go mod tidy"
        working-directory: "./backend"
        run: "go mod tidy"

      - name: "Install gotestsum"
        run: "go install gotest.tools/gotestsum@latest"

      - name: "Run unit tests"
        id: "ut-result"
        continue-on-error: true
        working-directory: "./backend"
        run: "gotestsum --junitfile report.xml --format testname -- -cover -coverprofile=coverage.out -short ./..."

      - name: "Check if tests failed"
        if: "steps.ut-result.outcome == 'failure'"
        run: |
          echo "Unit test: ${{ steps.ut-result.outcome }}"
          exit 1
